### ISSUE TITLE
Windows build is broken since 0.19

### ISSUE THREAD

**Issue by frol** [conda-forge/isl-feedstock#12]
Per the discussion in #11, there was a decision to merge 0.19 release for Linux and OS X while letting someone who is interested in Windows support to fix the Windows build in a separate PR. You are very welcome to contribute the fix!

**Comment by jakirkham** [comment]
Here's the error message.

```
1: Test command: 
Unable to find executable: isl-test
1/1 Test #1: isl_test .........................***Not Run   0.00 sec
0% tests passed, 1 tests failed out of 1
Total Test time (real) =   0.02 sec
The following tests FAILED:
	  1 - isl_test (Not Run)
Errors while running CTest
Traceback (most recent call last):
  File "C:\Miniconda36\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Miniconda36\lib\site-packages\conda_build\cli\main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "C:\Miniconda36\lib\site-packages\conda_build\cli\main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "C:\Miniconda36\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "C:\Miniconda36\lib\site-packages\conda_build\build.py", line 1524, in build_tree
    config=config)
  File "C:\Miniconda36\lib\site-packages\conda_build\build.py", line 1114, in build
    windows.build(m, build_file, config=config)
  File "C:\Miniconda36\lib\site-packages\conda_build\windows.py", line 232, in build
    check_call_env(cmd, cwd=src_dir)
  File "C:\Miniconda36\lib\site-packages\conda_build\utils.py", line 628, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "C:\Miniconda36\lib\site-packages\conda_build\utils.py", line 624, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "C:\Miniconda36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmd.exe', '/c', 'bld.bat']' returned non-zero exit status 8.
```

ref: https://ci.appveyor.com/project/conda-forge/isl-feedstock/build/1.0.4
